services:
  server:
    build: ./server
    container_name: server 
    ports:
      - "3001:3001"
    environment: 
      - mongodb+srv://poojithasiliveru2003:w4hoWDShRcP9qNgk@cluster0.pt3mqlg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  client:
    build: ./client
    container_name: client
    ports :
    - "3000:80"